-- 2. USER (150개 - 일단 10개만 예시, 나머지는 PL/SQL로)
INSERT INTO "USER" VALUES ('U001', '김철수', 'kim.cs@company.com', 'Team Leader', 'Y', SYSTIMESTAMP - INTERVAL '10' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U002', '이영희', 'lee.yh@company.com', 'Team Leader', 'Y', SYSTIMESTAMP - INTERVAL '5'  DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U003', '박민수', 'park.ms@company.com', 'Team Leader', 'Y', SYSTIMESTAMP - INTERVAL '8'  DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U004', '최지훈', 'choi.jh@company.com', 'Team Leader', 'Y', SYSTIMESTAMP - INTERVAL '3'  DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U005', '정수진', 'jung.sj@company.com', 'Team Leader', 'Y', SYSTIMESTAMP - INTERVAL '12' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U006', '강민아', 'kang.ma@company.com', 'Team Leader', 'Y', SYSTIMESTAMP - INTERVAL '7'  DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U007', '윤서연', 'yoon.sy@company.com', 'Team Leader', 'Y', SYSTIMESTAMP - INTERVAL '15' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U008', '임준호', 'lim.jh@company.com', 'Team Leader', 'Y', SYSTIMESTAMP - INTERVAL '20' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U009', '한지민', 'han.jm@company.com', 'Team Leader', 'Y', SYSTIMESTAMP - INTERVAL '6'  DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U010', '서동욱', 'seo.dw@company.com', 'Team Leader', 'Y', SYSTIMESTAMP - INTERVAL '9'  DAY, 'DEPT010');

-- 부서장 지정
UPDATE DEPARTMENT SET manager_user_id = 'U001' WHERE department_id = 'DEPT001';
UPDATE DEPARTMENT SET manager_user_id = 'U002' WHERE department_id = 'DEPT002';
UPDATE DEPARTMENT SET manager_user_id = 'U003' WHERE department_id = 'DEPT003';
UPDATE DEPARTMENT SET manager_user_id = 'U004' WHERE department_id = 'DEPT004';
UPDATE DEPARTMENT SET manager_user_id = 'U005' WHERE department_id = 'DEPT005';
UPDATE DEPARTMENT SET manager_user_id = 'U006' WHERE department_id = 'DEPT006';
UPDATE DEPARTMENT SET manager_user_id = 'U007' WHERE department_id = 'DEPT007';
UPDATE DEPARTMENT SET manager_user_id = 'U008' WHERE department_id = 'DEPT008';
UPDATE DEPARTMENT SET manager_user_id = 'U009' WHERE department_id = 'DEPT009';
UPDATE DEPARTMENT SET manager_user_id = 'U010' WHERE department_id = 'DEPT010';

commit;

-- 나머지 사용자들 (U011 ~ U300)
INSERT INTO "USER" VALUES ('U011', '오하환', 'user1000.1@company.com', 'Research Scientist', 'N', SYSTIMESTAMP - INTERVAL '35' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U012', '전도지', 'user1001.2@company.com', 'Data Scientist', 'N', SYSTIMESTAMP - INTERVAL '5' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U013', '류연민', 'user1002.3@company.com', 'Senior Engineer', 'N', SYSTIMESTAMP - INTERVAL '0' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U014', '신채시', 'user1003.4@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '34' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U015', '윤시채', 'user1004.5@company.com', 'UX Designer', 'Y', SYSTIMESTAMP - INTERVAL '29' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U016', '송소나', 'user1005.6@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '43' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U017', '백지예', 'user1006.7@company.com', 'DevOps Engineer', 'N', SYSTIMESTAMP - INTERVAL '37' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U018', '이빈범', 'user1007.8@company.com', 'QA Engineer', 'N', SYSTIMESTAMP - INTERVAL '40' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U019', '배수환', 'user1008.9@company.com', 'Security Analyst', 'N', SYSTIMESTAMP - INTERVAL '6' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U020', '강시경', 'user1009.10@company.com', 'HR Specialist', 'Y', SYSTIMESTAMP - INTERVAL '30' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U021', '안라원', 'user1010.1@company.com', 'ML Engineer', 'Y', SYSTIMESTAMP - INTERVAL '39' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U022', '노솔빈', 'user1011.2@company.com', 'Data Analyst', 'N', SYSTIMESTAMP - INTERVAL '39' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U023', '조호성', 'user1012.3@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '41' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U024', '박채서', 'user1013.4@company.com', 'Intern', 'Y', SYSTIMESTAMP - INTERVAL '40' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U025', '오은경', 'user1014.5@company.com', 'Product Manager', 'N', SYSTIMESTAMP - INTERVAL '44' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U026', '이규준', 'user1015.6@company.com', 'QA Engineer', 'N', SYSTIMESTAMP - INTERVAL '41' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U027', '박연지', 'user1016.7@company.com', 'DevOps Engineer', 'N', SYSTIMESTAMP - INTERVAL '7' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U028', '허규소', 'user1017.8@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '2' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U029', '허시재', 'user1018.9@company.com', 'Security Engineer', 'Y', SYSTIMESTAMP - INTERVAL '19' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U030', '김원유', 'user1019.10@company.com', 'Finance Analyst', 'N', SYSTIMESTAMP - INTERVAL '7' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U031', '고소세', 'user1020.1@company.com', 'Research Scientist', 'Y', SYSTIMESTAMP - INTERVAL '15' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U032', '한소현', 'user1021.2@company.com', 'Data Analyst', 'Y', SYSTIMESTAMP - INTERVAL '24' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U033', '김준은', 'user1022.3@company.com', 'QA Engineer', 'N', SYSTIMESTAMP - INTERVAL '23' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U034', '심빈솔', 'user1023.4@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '37' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U035', '신예태', 'user1024.5@company.com', 'Product Manager', 'Y', SYSTIMESTAMP - INTERVAL '26' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U036', '홍하서', 'user1025.6@company.com', 'QA Engineer', 'Y', SYSTIMESTAMP - INTERVAL '31' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U037', '조유솔', 'user1026.7@company.com', 'DevOps Engineer', 'N', SYSTIMESTAMP - INTERVAL '17' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U038', '남호한', 'user1027.8@company.com', 'Senior Engineer', 'Y', SYSTIMESTAMP - INTERVAL '44' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U039', '권원호', 'user1028.9@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '13' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U040', '허경진', 'user1029.10@company.com', 'HR Specialist', 'N', SYSTIMESTAMP - INTERVAL '28' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U041', '송진호', 'user1030.1@company.com', 'ML Engineer', 'Y', SYSTIMESTAMP - INTERVAL '23' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U042', '임소혁', 'user1031.2@company.com', 'ML Engineer', 'Y', SYSTIMESTAMP - INTERVAL '43' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U043', '강재경', 'user1032.3@company.com', 'Senior Engineer', 'N', SYSTIMESTAMP - INTERVAL '34' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U044', '송환린', 'user1033.4@company.com', 'ML Engineer', 'N', SYSTIMESTAMP - INTERVAL '3' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U045', '고빈나', 'user1034.5@company.com', 'Product Manager', 'N', SYSTIMESTAMP - INTERVAL '17' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U046', '허슬나', 'user1035.6@company.com', 'Team Leader', 'Y', SYSTIMESTAMP - INTERVAL '7' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U047', '황예시', 'user1036.7@company.com', 'DevOps Engineer', 'N', SYSTIMESTAMP - INTERVAL '5' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U048', '배재민', 'user1037.8@company.com', 'Quality Analyst', 'Y', SYSTIMESTAMP - INTERVAL '41' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U049', '남아지', 'user1038.9@company.com', 'Security Engineer', 'Y', SYSTIMESTAMP - INTERVAL '3' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U050', '강주재', 'user1039.10@company.com', 'HR Specialist', 'N', SYSTIMESTAMP - INTERVAL '15' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U051', '윤규린', 'user1040.1@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '36' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U052', '문소민', 'user1041.2@company.com', 'ML Engineer', 'Y', SYSTIMESTAMP - INTERVAL '4' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U053', '강혜혁', 'user1042.3@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '37' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U054', '류예지', 'user1043.4@company.com', 'Data Scientist', 'Y', SYSTIMESTAMP - INTERVAL '14' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U055', '배경호', 'user1044.5@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '9' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U056', '장진예', 'user1045.6@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '17' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U057', '전태예', 'user1046.7@company.com', 'DevOps Engineer', 'Y', SYSTIMESTAMP - INTERVAL '8' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U058', '박규예', 'user1047.8@company.com', 'Senior Engineer', 'N', SYSTIMESTAMP - INTERVAL '11' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U059', '허혁혜', 'user1048.9@company.com', 'Intern', 'Y', SYSTIMESTAMP - INTERVAL '42' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U060', '장원주', 'user1049.10@company.com', 'Finance Analyst', 'Y', SYSTIMESTAMP - INTERVAL '8' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U061', '고환채', 'user1050.1@company.com', 'Data Scientist', 'Y', SYSTIMESTAMP - INTERVAL '22' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U062', '한세린', 'user1051.2@company.com', 'ML Engineer', 'Y', SYSTIMESTAMP - INTERVAL '37' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U063', '백혁지', 'user1052.3@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '1' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U064', '조채은', 'user1053.4@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '16' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U065', '문라린', 'user1054.5@company.com', 'Product Manager', 'Y', SYSTIMESTAMP - INTERVAL '8' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U066', '허환라', 'user1055.6@company.com', 'Support Specialist', 'N', SYSTIMESTAMP - INTERVAL '33' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U067', '정경재', 'user1056.7@company.com', 'SRE', 'Y', SYSTIMESTAMP - INTERVAL '4' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U068', '배혜슬', 'user1057.8@company.com', 'Senior Engineer', 'N', SYSTIMESTAMP - INTERVAL '28' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U069', '문라솔', 'user1058.9@company.com', 'Security Analyst', 'N', SYSTIMESTAMP - INTERVAL '32' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U070', '배진주', 'user1059.10@company.com', 'HR Specialist', 'Y', SYSTIMESTAMP - INTERVAL '28' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U071', '오환준', 'user1060.1@company.com', 'ML Engineer', 'Y', SYSTIMESTAMP - INTERVAL '39' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U072', '박혁도', 'user1061.2@company.com', 'ML Engineer', 'Y', SYSTIMESTAMP - INTERVAL '42' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U073', '장빈소', 'user1062.3@company.com', 'Product Manager', 'N', SYSTIMESTAMP - INTERVAL '29' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U074', '윤나영', 'user1063.4@company.com', 'Intern', 'Y', SYSTIMESTAMP - INTERVAL '3' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U075', '황슬현', 'user1064.5@company.com', 'Business Analyst', 'N', SYSTIMESTAMP - INTERVAL '25' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U076', '백예시', 'user1065.6@company.com', 'Customer Success', 'N', SYSTIMESTAMP - INTERVAL '43' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U077', '고환준', 'user1066.7@company.com', 'SRE', 'Y', SYSTIMESTAMP - INTERVAL '31' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U078', '윤우경', 'user1067.8@company.com', 'Team Leader', 'N', SYSTIMESTAMP - INTERVAL '4' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U079', '한혁원', 'user1068.9@company.com', 'Security Analyst', 'Y', SYSTIMESTAMP - INTERVAL '20' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U080', '백서준', 'user1069.10@company.com', 'Finance Analyst', 'Y', SYSTIMESTAMP - INTERVAL '4' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U081', '임수혜', 'user1070.1@company.com', 'ML Engineer', 'Y', SYSTIMESTAMP - INTERVAL '17' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U082', '서아은', 'user1071.2@company.com', 'Data Scientist', 'N', SYSTIMESTAMP - INTERVAL '24' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U083', '권주예', 'user1072.3@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '29' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U084', '임지빈', 'user1073.4@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '6' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U085', '남경영', 'user1074.5@company.com', 'Business Analyst', 'Y', SYSTIMESTAMP - INTERVAL '41' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U086', '정시윤', 'user1075.6@company.com', 'Intern', 'Y', SYSTIMESTAMP - INTERVAL '27' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U087', '신혁민', 'user1076.7@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '14' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U088', '조예지', 'user1077.8@company.com', 'Senior Engineer', 'N', SYSTIMESTAMP - INTERVAL '21' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U089', '한연현', 'user1078.9@company.com', 'Security Engineer', 'N', SYSTIMESTAMP - INTERVAL '25' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U090', '손빈재', 'user1079.10@company.com', 'Team Leader', 'N', SYSTIMESTAMP - INTERVAL '6' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U091', '서원경', 'user1080.1@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '27' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U092', '정수소', 'user1081.2@company.com', 'Data Analyst', 'N', SYSTIMESTAMP - INTERVAL '42' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U093', '남현시', 'user1082.3@company.com', 'Product Manager', 'N', SYSTIMESTAMP - INTERVAL '23' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U094', '이환민', 'user1083.4@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '43' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U095', '한세은', 'user1084.5@company.com', 'Product Manager', 'N', SYSTIMESTAMP - INTERVAL '4' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U096', '박규채', 'user1085.6@company.com', 'Customer Success', 'Y', SYSTIMESTAMP - INTERVAL '5' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U097', '신시현', 'user1086.7@company.com', 'DevOps Engineer', 'Y', SYSTIMESTAMP - INTERVAL '27' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U098', '임도은', 'user1087.8@company.com', 'Quality Analyst', 'Y', SYSTIMESTAMP - INTERVAL '23' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U099', '정태연', 'user1088.9@company.com', 'Security Engineer', 'Y', SYSTIMESTAMP - INTERVAL '35' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U100', '최민호', 'user1089.10@company.com', 'Finance Analyst', 'Y', SYSTIMESTAMP - INTERVAL '37' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U101', '김혁우', 'user1090.1@company.com', 'ML Engineer', 'N', SYSTIMESTAMP - INTERVAL '42' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U102', '손예수', 'user1091.2@company.com', 'ML Engineer', 'Y', SYSTIMESTAMP - INTERVAL '26' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U103', '박윤채', 'user1092.3@company.com', 'QA Engineer', 'N', SYSTIMESTAMP - INTERVAL '42' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U104', '임소수', 'user1093.4@company.com', 'ML Engineer', 'N', SYSTIMESTAMP - INTERVAL '3' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U105', '최한호', 'user1094.5@company.com', 'Business Analyst', 'N', SYSTIMESTAMP - INTERVAL '38' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U106', '이연도', 'user1095.6@company.com', 'Support Specialist', 'N', SYSTIMESTAMP - INTERVAL '22' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U107', '김하나', 'user1096.7@company.com', 'Intern', 'Y', SYSTIMESTAMP - INTERVAL '36' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U108', '강빈주', 'user1097.8@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '9' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U109', '류서준', 'user1098.9@company.com', 'Security Analyst', 'N', SYSTIMESTAMP - INTERVAL '14' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U110', '전수환', 'user1099.10@company.com', 'Finance Analyst', 'Y', SYSTIMESTAMP - INTERVAL '22' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U111', '조한유', 'user1100.1@company.com', 'ML Engineer', 'N', SYSTIMESTAMP - INTERVAL '7' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U112', '안유준', 'user1101.2@company.com', 'Data Analyst', 'N', SYSTIMESTAMP - INTERVAL '36' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U113', '권슬호', 'user1102.3@company.com', 'Intern', 'Y', SYSTIMESTAMP - INTERVAL '27' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U114', '장린시', 'user1103.4@company.com', 'MLOps Engineer', 'Y', SYSTIMESTAMP - INTERVAL '38' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U115', '김유성', 'user1104.5@company.com', 'Business Analyst', 'N', SYSTIMESTAMP - INTERVAL '1' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U116', '권소빈', 'user1105.6@company.com', 'Intern', 'Y', SYSTIMESTAMP - INTERVAL '17' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U117', '오세경', 'user1106.7@company.com', 'Senior Engineer', 'N', SYSTIMESTAMP - INTERVAL '21' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U118', '문우현', 'user1107.8@company.com', 'Quality Analyst', 'N', SYSTIMESTAMP - INTERVAL '0' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U119', '허준시', 'user1108.9@company.com', 'Security Analyst', 'Y', SYSTIMESTAMP - INTERVAL '9' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U120', '송하한', 'user1109.10@company.com', 'HR Specialist', 'N', SYSTIMESTAMP - INTERVAL '4' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U121', '배진진', 'user1110.1@company.com', 'Research Scientist', 'Y', SYSTIMESTAMP - INTERVAL '40' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U122', '장성예', 'user1111.2@company.com', 'ML Engineer', 'Y', SYSTIMESTAMP - INTERVAL '5' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U123', '류우현', 'user1112.3@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '24' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U124', '안슬채', 'user1113.4@company.com', 'Data Scientist', 'N', SYSTIMESTAMP - INTERVAL '29' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U125', '정세현', 'user1114.5@company.com', 'Product Manager', 'N', SYSTIMESTAMP - INTERVAL '10' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U126', '심빈서', 'user1115.6@company.com', 'Customer Success', 'N', SYSTIMESTAMP - INTERVAL '19' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U127', '허우도', 'user1116.7@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '36' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U128', '이성아', 'user1117.8@company.com', 'Quality Analyst', 'Y', SYSTIMESTAMP - INTERVAL '3' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U129', '서한영', 'user1118.9@company.com', 'Senior Engineer', 'Y', SYSTIMESTAMP - INTERVAL '10' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U130', '심예나', 'user1119.10@company.com', 'HR Specialist', 'Y', SYSTIMESTAMP - INTERVAL '43' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U131', '장하지', 'user1120.1@company.com', 'Intern', 'Y', SYSTIMESTAMP - INTERVAL '17' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U132', '노지라', 'user1121.2@company.com', 'ML Engineer', 'N', SYSTIMESTAMP - INTERVAL '42' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U133', '박준유', 'user1122.3@company.com', 'Senior Engineer', 'N', SYSTIMESTAMP - INTERVAL '31' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U134', '조환우', 'user1123.4@company.com', 'ML Engineer', 'N', SYSTIMESTAMP - INTERVAL '26' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U135', '심원서', 'user1124.5@company.com', 'Business Analyst', 'N', SYSTIMESTAMP - INTERVAL '13' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U136', '문환원', 'user1125.6@company.com', 'Customer Success', 'Y', SYSTIMESTAMP - INTERVAL '22' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U137', '이지린', 'user1126.7@company.com', 'SRE', 'N', SYSTIMESTAMP - INTERVAL '7' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U138', '심수범', 'user1127.8@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '43' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U139', '서세성', 'user1128.9@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '33' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U140', '고범혁', 'user1129.10@company.com', 'Finance Analyst', 'N', SYSTIMESTAMP - INTERVAL '2' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U141', '권현도', 'user1130.1@company.com', 'ML Engineer', 'Y', SYSTIMESTAMP - INTERVAL '25' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U142', '이빈환', 'user1131.2@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '0' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U143', '고라경', 'user1132.3@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '19' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U144', '장민수', 'user1133.4@company.com', 'Data Scientist', 'Y', SYSTIMESTAMP - INTERVAL '8' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U145', '허원한', 'user1134.5@company.com', 'Business Analyst', 'N', SYSTIMESTAMP - INTERVAL '18' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U146', '문주나', 'user1135.6@company.com', 'Support Specialist', 'N', SYSTIMESTAMP - INTERVAL '7' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U147', '장라주', 'user1136.7@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '31' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U148', '최소나', 'user1137.8@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '11' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U149', '조준예', 'user1138.9@company.com', 'Security Engineer', 'Y', SYSTIMESTAMP - INTERVAL '24' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U150', '송예범', 'user1139.10@company.com', 'Operations Manager', 'Y', SYSTIMESTAMP - INTERVAL '32' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U151', '강한민', 'user1140.1@company.com', 'Research Scientist', 'N', SYSTIMESTAMP - INTERVAL '4' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U152', '홍나수', 'user1141.2@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '2' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U153', '권민주', 'user1142.3@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '1' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U154', '한소혁', 'user1143.4@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '4' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U155', '전현예', 'user1144.5@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '36' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U156', '장도린', 'user1145.6@company.com', 'Support Specialist', 'N', SYSTIMESTAMP - INTERVAL '36' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U157', '전현한', 'user1146.7@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '45' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U158', '김환아', 'user1147.8@company.com', 'Quality Analyst', 'N', SYSTIMESTAMP - INTERVAL '18' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U159', '송민재', 'user1148.9@company.com', 'Intern', 'Y', SYSTIMESTAMP - INTERVAL '25' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U160', '손혁태', 'user1149.10@company.com', 'Finance Analyst', 'Y', SYSTIMESTAMP - INTERVAL '20' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U161', '송린성', 'user1150.1@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '39' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U162', '김라호', 'user1151.2@company.com', 'Data Scientist', 'N', SYSTIMESTAMP - INTERVAL '44' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U163', '홍유혜', 'user1152.3@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '5' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U164', '손시예', 'user1153.4@company.com', 'MLOps Engineer', 'N', SYSTIMESTAMP - INTERVAL '6' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U165', '배윤서', 'user1154.5@company.com', 'Intern', 'Y', SYSTIMESTAMP - INTERVAL '27' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U166', '윤윤성', 'user1155.6@company.com', 'Customer Success', 'N', SYSTIMESTAMP - INTERVAL '33' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U167', '이주한', 'user1156.7@company.com', 'SRE', 'Y', SYSTIMESTAMP - INTERVAL '25' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U168', '홍소진', 'user1157.8@company.com', 'Quality Analyst', 'N', SYSTIMESTAMP - INTERVAL '21' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U169', '백윤세', 'user1158.9@company.com', 'Security Engineer', 'Y', SYSTIMESTAMP - INTERVAL '21' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U170', '안영규', 'user1159.10@company.com', 'Operations Manager', 'Y', SYSTIMESTAMP - INTERVAL '4' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U171', '신주경', 'user1160.1@company.com', 'Data Scientist', 'Y', SYSTIMESTAMP - INTERVAL '33' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U172', '박원원', 'user1161.2@company.com', 'Data Analyst', 'Y', SYSTIMESTAMP - INTERVAL '22' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U173', '홍시슬', 'user1162.3@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '41' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U174', '오환경', 'user1163.4@company.com', 'ML Engineer', 'Y', SYSTIMESTAMP - INTERVAL '15' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U175', '심재혜', 'user1164.5@company.com', 'Business Analyst', 'Y', SYSTIMESTAMP - INTERVAL '9' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U176', '한규솔', 'user1165.6@company.com', 'Customer Success', 'N', SYSTIMESTAMP - INTERVAL '12' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U177', '조성예', 'user1166.7@company.com', 'SRE', 'Y', SYSTIMESTAMP - INTERVAL '38' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U178', '손원유', 'user1167.8@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '41' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U179', '배영우', 'user1168.9@company.com', 'Team Leader', 'Y', SYSTIMESTAMP - INTERVAL '11' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U180', '윤우서', 'user1169.10@company.com', 'Business Analyst', 'N', SYSTIMESTAMP - INTERVAL '29' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U181', '백환범', 'user1170.1@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '43' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U182', '안성주', 'user1171.2@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '40' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U183', '문예라', 'user1172.3@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '9' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U184', '배채하', 'user1173.4@company.com', 'Data Scientist', 'N', SYSTIMESTAMP - INTERVAL '4' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U185', '배소연', 'user1174.5@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '28' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U186', '배아하', 'user1175.6@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '17' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U187', '황주아', 'user1176.7@company.com', 'DevOps Engineer', 'Y', SYSTIMESTAMP - INTERVAL '22' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U188', '송태소', 'user1177.8@company.com', 'Team Leader', 'Y', SYSTIMESTAMP - INTERVAL '19' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U189', '심경태', 'user1178.9@company.com', 'Security Analyst', 'N', SYSTIMESTAMP - INTERVAL '28' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U190', '심라예', 'user1179.10@company.com', 'Operations Manager', 'Y', SYSTIMESTAMP - INTERVAL '3' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U191', '배채지', 'user1180.1@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '18' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U192', '오솔도', 'user1181.2@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '41' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U193', '황서한', 'user1182.3@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '39' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U194', '오채한', 'user1183.4@company.com', 'MLOps Engineer', 'N', SYSTIMESTAMP - INTERVAL '29' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U195', '류소윤', 'user1184.5@company.com', 'UX Designer', 'Y', SYSTIMESTAMP - INTERVAL '28' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U196', '장유은', 'user1185.6@company.com', 'QA Engineer', 'Y', SYSTIMESTAMP - INTERVAL '20' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U197', '김하현', 'user1186.7@company.com', 'DevOps Engineer', 'N', SYSTIMESTAMP - INTERVAL '32' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U198', '강린린', 'user1187.8@company.com', 'Senior Engineer', 'Y', SYSTIMESTAMP - INTERVAL '3' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U199', '강지한', 'user1188.9@company.com', 'Security Engineer', 'N', SYSTIMESTAMP - INTERVAL '6' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U200', '한연진', 'user1189.10@company.com', 'Finance Analyst', 'N', SYSTIMESTAMP - INTERVAL '45' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U201', '장태은', 'user1190.1@company.com', 'Intern', 'Y', SYSTIMESTAMP - INTERVAL '32' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U202', '조태나', 'user1191.2@company.com', 'Data Analyst', 'Y', SYSTIMESTAMP - INTERVAL '2' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U203', '최예연', 'user1192.3@company.com', 'Product Manager', 'Y', SYSTIMESTAMP - INTERVAL '45' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U204', '강채원', 'user1193.4@company.com', 'Data Scientist', 'N', SYSTIMESTAMP - INTERVAL '28' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U205', '안환우', 'user1194.5@company.com', 'Intern', 'Y', SYSTIMESTAMP - INTERVAL '23' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U206', '신린경', 'user1195.6@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '18' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U207', '전재민', 'user1196.7@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '26' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U208', '조주윤', 'user1197.8@company.com', 'Quality Analyst', 'N', SYSTIMESTAMP - INTERVAL '43' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U209', '조범시', 'user1198.9@company.com', 'Security Engineer', 'Y', SYSTIMESTAMP - INTERVAL '40' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U210', '류혁연', 'user1199.10@company.com', 'Business Analyst', 'N', SYSTIMESTAMP - INTERVAL '4' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U211', '이나빈', 'user1200.1@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '6' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U212', '심연유', 'user1201.2@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '18' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U213', '장솔진', 'user1202.3@company.com', 'Team Leader', 'N', SYSTIMESTAMP - INTERVAL '42' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U214', '문소혁', 'user1203.4@company.com', 'ML Engineer', 'Y', SYSTIMESTAMP - INTERVAL '21' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U215', '조규주', 'user1204.5@company.com', 'Business Analyst', 'Y', SYSTIMESTAMP - INTERVAL '37' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U216', '조지지', 'user1205.6@company.com', 'Intern', 'Y', SYSTIMESTAMP - INTERVAL '22' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U217', '남영현', 'user1206.7@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '41' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U218', '노지진', 'user1207.8@company.com', 'Senior Engineer', 'N', SYSTIMESTAMP - INTERVAL '8' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U219', '남민하', 'user1208.9@company.com', 'Security Analyst', 'Y', SYSTIMESTAMP - INTERVAL '19' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U220', '박예수', 'user1209.10@company.com', 'HR Specialist', 'N', SYSTIMESTAMP - INTERVAL '41' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U221', '윤현혜', 'user1210.1@company.com', 'Data Scientist', 'N', SYSTIMESTAMP - INTERVAL '8' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U222', '정윤라', 'user1211.2@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '41' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U223', '신시경', 'user1212.3@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '32' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U224', '오현민', 'user1213.4@company.com', 'Data Scientist', 'N', SYSTIMESTAMP - INTERVAL '1' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U225', '고혁라', 'user1214.5@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '19' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U226', '남수영', 'user1215.6@company.com', 'Support Specialist', 'Y', SYSTIMESTAMP - INTERVAL '13' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U227', '서린규', 'user1216.7@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '31' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U228', '홍민지', 'user1217.8@company.com', 'QA Engineer', 'Y', SYSTIMESTAMP - INTERVAL '14' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U229', '황민세', 'user1218.9@company.com', 'Security Analyst', 'Y', SYSTIMESTAMP - INTERVAL '9' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U230', '장윤경', 'user1219.10@company.com', 'HR Specialist', 'Y', SYSTIMESTAMP - INTERVAL '18' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U231', '문소채', 'user1220.1@company.com', 'Data Scientist', 'Y', SYSTIMESTAMP - INTERVAL '32' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U232', '임범범', 'user1221.2@company.com', 'Data Analyst', 'Y', SYSTIMESTAMP - INTERVAL '42' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U233', '김윤예', 'user1222.3@company.com', 'QA Engineer', 'N', SYSTIMESTAMP - INTERVAL '39' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U234', '노혁연', 'user1223.4@company.com', 'ML Engineer', 'Y', SYSTIMESTAMP - INTERVAL '38' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U235', '백범원', 'user1224.5@company.com', 'Product Manager', 'N', SYSTIMESTAMP - INTERVAL '9' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U236', '고주규', 'user1225.6@company.com', 'Intern', 'Y', SYSTIMESTAMP - INTERVAL '11' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U237', '김하주', 'user1226.7@company.com', 'DevOps Engineer', 'Y', SYSTIMESTAMP - INTERVAL '28' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U238', '남윤범', 'user1227.8@company.com', 'QA Engineer', 'Y', SYSTIMESTAMP - INTERVAL '26' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U239', '류은경', 'user1228.9@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '43' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U240', '조우환', 'user1229.10@company.com', 'HR Specialist', 'Y', SYSTIMESTAMP - INTERVAL '28' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U241', '고유태', 'user1230.1@company.com', 'Research Scientist', 'N', SYSTIMESTAMP - INTERVAL '28' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U242', '윤혜빈', 'user1231.2@company.com', 'Data Scientist', 'Y', SYSTIMESTAMP - INTERVAL '34' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U243', '임연솔', 'user1232.3@company.com', 'Senior Engineer', 'Y', SYSTIMESTAMP - INTERVAL '19' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U244', '고준도', 'user1233.4@company.com', 'Team Leader', 'N', SYSTIMESTAMP - INTERVAL '12' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U245', '윤빈린', 'user1234.5@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '43' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U246', '문진유', 'user1235.6@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '29' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U247', '이솔채', 'user1236.7@company.com', 'Senior Engineer', 'N', SYSTIMESTAMP - INTERVAL '24' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U248', '오하라', 'user1237.8@company.com', 'QA Engineer', 'N', SYSTIMESTAMP - INTERVAL '10' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U249', '전호라', 'user1238.9@company.com', 'Security Analyst', 'Y', SYSTIMESTAMP - INTERVAL '38' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U250', '안범수', 'user1239.10@company.com', 'Finance Analyst', 'Y', SYSTIMESTAMP - INTERVAL '16' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U251', '전성유', 'user1240.1@company.com', 'Data Scientist', 'Y', SYSTIMESTAMP - INTERVAL '41' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U252', '조도은', 'user1241.2@company.com', 'ML Engineer', 'N', SYSTIMESTAMP - INTERVAL '23' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U253', '권한시', 'user1242.3@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '45' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U254', '이예호', 'user1243.4@company.com', 'ML Engineer', 'Y', SYSTIMESTAMP - INTERVAL '18' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U255', '이슬준', 'user1244.5@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '10' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U256', '고채슬', 'user1245.6@company.com', 'Support Specialist', 'N', SYSTIMESTAMP - INTERVAL '28' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U257', '류범예', 'user1246.7@company.com', 'DevOps Engineer', 'Y', SYSTIMESTAMP - INTERVAL '27' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U258', '이혁예', 'user1247.8@company.com', 'Quality Analyst', 'Y', SYSTIMESTAMP - INTERVAL '14' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U259', '고한솔', 'user1248.9@company.com', 'Security Engineer', 'N', SYSTIMESTAMP - INTERVAL '22' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U260', '박아연', 'user1249.10@company.com', 'Operations Manager', 'Y', SYSTIMESTAMP - INTERVAL '26' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U261', '한라연', 'user1250.1@company.com', 'Data Scientist', 'Y', SYSTIMESTAMP - INTERVAL '25' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U262', '심혜예', 'user1251.2@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '15' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U263', '임민환', 'user1252.3@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '5' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U264', '심태환', 'user1253.4@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '14' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U265', '이혁도', 'user1254.5@company.com', 'Business Analyst', 'Y', SYSTIMESTAMP - INTERVAL '20' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U266', '황혁재', 'user1255.6@company.com', 'Support Specialist', 'Y', SYSTIMESTAMP - INTERVAL '45' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U267', '고시현', 'user1256.7@company.com', 'DevOps Engineer', 'N', SYSTIMESTAMP - INTERVAL '9' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U268', '허규린', 'user1257.8@company.com', 'Senior Engineer', 'Y', SYSTIMESTAMP - INTERVAL '2' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U269', '윤우태', 'user1258.9@company.com', 'Senior Engineer', 'N', SYSTIMESTAMP - INTERVAL '30' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U270', '손혁환', 'user1259.10@company.com', 'Team Leader', 'Y', SYSTIMESTAMP - INTERVAL '45' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U271', '손하수', 'user1260.1@company.com', 'Data Scientist', 'N', SYSTIMESTAMP - INTERVAL '28' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U272', '서영재', 'user1261.2@company.com', 'Data Analyst', 'Y', SYSTIMESTAMP - INTERVAL '5' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U273', '이민채', 'user1262.3@company.com', 'Intern', 'Y', SYSTIMESTAMP - INTERVAL '16' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U274', '고나혜', 'user1263.4@company.com', 'ML Engineer', 'Y', SYSTIMESTAMP - INTERVAL '9' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U275', '고성아', 'user1264.5@company.com', 'Engineer', 'N', SYSTIMESTAMP - INTERVAL '7' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U276', '전환서', 'user1265.6@company.com', 'QA Engineer', 'N', SYSTIMESTAMP - INTERVAL '15' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U277', '서빈호', 'user1266.7@company.com', 'SRE', 'N', SYSTIMESTAMP - INTERVAL '7' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U278', '박예라', 'user1267.8@company.com', 'Senior Engineer', 'Y', SYSTIMESTAMP - INTERVAL '15' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U279', '한주채', 'user1268.9@company.com', 'Security Analyst', 'N', SYSTIMESTAMP - INTERVAL '40' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U280', '홍성경', 'user1269.10@company.com', 'Operations Manager', 'N', SYSTIMESTAMP - INTERVAL '4' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U281', '안주혁', 'user1270.1@company.com', 'Engineer', 'Y', SYSTIMESTAMP - INTERVAL '31' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U282', '오솔수', 'user1271.2@company.com', 'ML Engineer', 'Y', SYSTIMESTAMP - INTERVAL '40' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U283', '윤하우', 'user1272.3@company.com', 'QA Engineer', 'Y', SYSTIMESTAMP - INTERVAL '45' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U284', '정범하', 'user1273.4@company.com', 'Data Scientist', 'Y', SYSTIMESTAMP - INTERVAL '18' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U285', '박소시', 'user1274.5@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '0' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U286', '고환시', 'user1275.6@company.com', 'QA Engineer', 'N', SYSTIMESTAMP - INTERVAL '15' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U287', '최현환', 'user1276.7@company.com', 'SRE', 'N', SYSTIMESTAMP - INTERVAL '11' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U288', '권혜은', 'user1277.8@company.com', 'Quality Analyst', 'Y', SYSTIMESTAMP - INTERVAL '33' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U289', '백하호', 'user1278.9@company.com', 'Security Analyst', 'N', SYSTIMESTAMP - INTERVAL '4' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U290', '조솔아', 'user1279.10@company.com', 'Business Analyst', 'Y', SYSTIMESTAMP - INTERVAL '24' DAY, 'DEPT010');
INSERT INTO "USER" VALUES ('U291', '남린소', 'user1280.1@company.com', 'ML Engineer', 'N', SYSTIMESTAMP - INTERVAL '2' DAY, 'DEPT001');
INSERT INTO "USER" VALUES ('U292', '허현환', 'user1281.2@company.com', 'Data Scientist', 'N', SYSTIMESTAMP - INTERVAL '23' DAY, 'DEPT002');
INSERT INTO "USER" VALUES ('U293', '안재수', 'user1282.3@company.com', 'QA Engineer', 'N', SYSTIMESTAMP - INTERVAL '1' DAY, 'DEPT003');
INSERT INTO "USER" VALUES ('U294', '홍경태', 'user1283.4@company.com', 'ML Engineer', 'N', SYSTIMESTAMP - INTERVAL '4' DAY, 'DEPT004');
INSERT INTO "USER" VALUES ('U295', '강유은', 'user1284.5@company.com', 'Product Manager', 'N', SYSTIMESTAMP - INTERVAL '15' DAY, 'DEPT005');
INSERT INTO "USER" VALUES ('U296', '임한원', 'user1285.6@company.com', 'Customer Success', 'Y', SYSTIMESTAMP - INTERVAL '37' DAY, 'DEPT006');
INSERT INTO "USER" VALUES ('U297', '박한지', 'user1286.7@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '8' DAY, 'DEPT007');
INSERT INTO "USER" VALUES ('U298', '신하호', 'user1287.8@company.com', 'Quality Analyst', 'Y', SYSTIMESTAMP - INTERVAL '22' DAY, 'DEPT008');
INSERT INTO "USER" VALUES ('U299', '허준범', 'user1288.9@company.com', 'Intern', 'N', SYSTIMESTAMP - INTERVAL '41' DAY, 'DEPT009');
INSERT INTO "USER" VALUES ('U300', '윤진지', 'user1289.10@company.com', 'Business Analyst', 'Y', SYSTIMESTAMP - INTERVAL '43' DAY, 'DEPT010');

commit;