INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL001', 'Mistral 7B', 'Transformer (Dense)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL002', 'Mixtral 8x7B', 'Transformer (MoE)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL003', 'Mixtral 8x22B', 'Transformer (MoE)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL004', 'Qwen2.5-0.5B', 'Transformer (Dense)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL005', 'Qwen2.5-1.5B', 'Transformer (Dense)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL006', 'Qwen2.5-3B',   'Transformer (Dense)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL007', 'Qwen2.5-7B',   'Transformer (Dense)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL008', 'Qwen2.5-14B',  'Transformer (Dense)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL009', 'Qwen2.5-32B',  'Transformer (Dense)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL010', 'Qwen2.5-72B',  'Transformer (Dense)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL011', 'Llama 3.1-8B',  'Transformer (Dense)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL012', 'Llama 3.1-70B', 'Transformer (Dense)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL013', 'Falcon 7B',  'Transformer (Dense)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL014', 'Falcon 40B', 'Transformer (Dense)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL015', 'Falcon Mamba 7B', 'SSM');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL016', 'BLOOM 176B', 'Transformer (Dense)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL017', 'MPT-7B',        'Transformer (Dense)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL018', 'gpt-oss-20B',      'Transformer (Dense)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL019', 'gpt-oss-120B',  'Transformer (Dense)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL020', 'Pythia-12B',    'Transformer (Dense)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL021', 'Llama 2-7B', 'Transformer (Dense)');
INSERT INTO MODEL (model_id, model_name, model_type) VALUES ('MDL022', 'Llama 2-70B', 'Transformer (Dense)');
commit;